builds:
- goos:
  - linux
  - darwin
  - openbsd
  - freebsd
  - windows
  ldflags:
  - -s -w
  - -X main.version=v{{.Version}}
  - -X main.commit={{.Commit}}
archives:
- name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format: binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
